#!/bin/sh
#
# Start the Redlooper UI application....
#

case "$1" in
  start)
    echo "Starting RedlooperApp..."
    redlooper_app
    ;;
  stop)
    echo -n "Stopping RedlooperApp..."
    #/sbin/ifdown -a
    ;;
  restart|reload)
    "$0" stop
    "$0" start
    ;;
  *)
    echo $"Usage: $0 {start|stop|restart}"
    exit 1
esac

exit $?
